### PR TITLE
Fix Model#settings.acls doc type signature

### PR DESCRIPTION
**Pull request by alFReD-NSH**
### Description

It fixes Model#settings.acls doc type signature, it's an array of objects.

#### Related issues

- None

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
@alFReD-NSH thank you for the contribution and sorry for the delay in responding to your pull request. Could you please rebase your change on top of the latest master? @0candy has recently landed #3448 which is changing the same line of code.

@0candy could you PTAL at the proposed type definition? I believe strong-docs supports both `Object[]` and `Array.<Object>` syntax, I don't know if we have any formal rules on which syntax to use. @superkhau do you happen to know that?

**Comment by 0candy** [comment]
@bajtos I agree that both syntax works, not sure if we have a preference. Maybe @crandmck or @superkhau will know. Will wait for them to comment.

**Comment by superkhau** [comment]
@bajtos I don't think we have a standard ATM -- but I agree with you, we should pick one and roll with it. @crandmck can decide which way to go since this is more his area.

**Comment by crandmck** [comment]
From https://github.com/strongloop/loopback-connector/issues/54 it appears that `Object[]` notation won't work in doc comments, so you must use `Array.<Object>`.

**Comment by superkhau** [comment]
Thanks @crandmck, good to know. We should have a simple list of available/standard type definitions we use somewhere (like our coding guidelines) -- something to consider in the future.

**Comment by bajtos** [comment]
I have rebased the patch myself, fixed the type to `Array.<Object>` and force-pushed to @alFReD-NSH feature branch. Let's wait for CI results before merging.

**Comment by bajtos** [comment]
Landed, thank you @alFReD-NSH for the contribution!

**Pull request merged**
