### PR TITLE
change password to string if it is detected as number

### PR DESCRIPTION
**Pull request by dhirender-tyagi**
server get break down if i give password as numeric in reset password case because it is handled as number so number.indexOf() get break

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by ritch** [comment]
@dhirender-tyagi can you sign the CLA? Otherwise this LGTM and can be merged.

**Comment by dhirender-tyagi** [comment]
@ritch I have signed the CLA.

**Comment by dhirenderbp** [comment]
Is there is any feedback that does't received

**Comment by dhirender-tyagi** [comment]
Is there any feedback that is doesn't get

**Comment by 0candy** [comment]
Already fixed by https://github.com/strongloop/loopback/issues/1437

**Pull request closed without merging**
