### PR TITLE
Do not include redundant ports in verify links

### PR DESCRIPTION
**Pull request by gausie**
If the protocol and port match we can ignore the port for a more visually appealing link.

### CODE REVIEW

**Comment by bajtos** [comment]
Thank you for the pull request. Is there a reasonably easy way how to write an automate (unit) test to verify the implementation and prevent regressions in the future?

@ritch you are more familiar with this particular code, could you please review?

**Comment by ritch** [comment]
Test please

**Comment by ritch** [comment]
Code looks fine

**Comment by gausie** [comment]
Added unit testing for the new feature, and fixed a bug that it uncovered!

**Comment by bajtos** [comment]
I have squashed the commits into a single one using `git rebase -i master` and landed the patch via  c55f19a. Thank you for the contribution!

**Pull request closed without merging**
