### PR TITLE
Revert "Validate on updateAll"

### PR DESCRIPTION
**Pull request by ssh24**
# Description

This change should not have gone in. The backwards compatibility fix needs to go in juggler's DAO for validation on `updateAll`.

Reverts strongloop/loopback#3541

### CODE REVIEW

**Comment by ssh24** [comment]
This PR can be reverted once the backward compatibility fix on Juggler lands https://github.com/strongloop/loopback-datasource-juggler/pull/1451

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@bajtos I am not sure why this needs awaiting for Juggler to be released? CI fetches the latest Juggler from the ci registry.

**Comment by bajtos** [comment]
> I am not sure why this needs awaiting for Juggler to be released? CI fetches the latest Juggler from the ci registry.

Ah, I forgot that we have modified Travis config to use our staging registry too. Feel free to land this pull request then.

There is still the issue with community contributors who will see `npm test` failing in their local git-cloned repositories, because most people (including me) are installing from the official npmjs.org registry. But that's just a temporary thing that has a workaround (e.g. `npm link` juggler master).

**Pull request merged**
