### PR TITLE
Fix: treat empty access token string as undefined

### PR DESCRIPTION
**Pull request by andrey-abramow**
#### Related issues
- Fixes  https://github.com/strongloop/loopback/issues/4078

### CODE REVIEW

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Windows CI failures are caused by a problem in our CI infrastructure, I'll ignore them.

```
Wiping out workspace first.
java.nio.file.FileSystemException: D:\workspace\loopback\68dfec3a\xunit.xml: The process cannot access the file because it is being used by another process.
```

**Comment by bajtos** [comment]
Landed, thank you 🙇

**Comment by andrey-abramow** [comment]
@bajtos Thank you too the help and quick responses! 🙇

**Pull request merged**
