### PR TITLE
Fix typo in jsdoc

### PR DESCRIPTION
**Pull request by SiegfriedEhret**
### Description

Update a jsdoc thing to match the argument name.

(related issue & checklist not applicable).

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
The CI build failures are unrelated to this change, I'll investigate them ASAP.

I have landed the pull request, thank you @SiegfriedEhret for your contribution 🎉

**Comment by SiegfriedEhret** [comment]
Thanks @bajtos !
Just a small change, I hope I'll be able to help again ! Peace !

**Pull request merged**
