### PR TITLE
Add back loopback properties like modelBuilder

### PR DESCRIPTION
**Pull request by bajtos**
The commit b917075 (#1212) accidentally removed a couple of properties, this commit is bringing them back:

 - loopback.modelRegistry
 - loopback.defaultDataSources

A unit-test was added to prevent this kind of regressions in the future.

/to @ritch please review
/cc @fabien @PradnyaBaviskar

### CODE REVIEW

**Comment by bajtos** [comment]
The list of expected property names comes from `v2.15.0`

**Comment by ritch** [comment]
LGTM

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
Released as `loopback@2.16.1`.

/cc @fabien @PradnyaBaviskar

**Pull request merged**
