### PR TITLE
Feature: Globalize error messages

### PR DESCRIPTION
**Pull request by greaterweb**
PR for #932

Updates complete with tests.

### CODE REVIEW

**Comment by raymondfeng** [comment]
@greaterweb Great stuff. Do you plan to create resource bundles that maps error code to localized messages?

**Comment by greaterweb** [comment]
@raymondfeng I'll be working on something for an angular project I have going on. I would happy to contribute back. Did you have a specific approach in mind?

**Comment by bajtos** [comment]
@greaterweb thank you for the pull request, sorry that we are taking so long to get it reviewed. I'll take a close look in the next few days.

**Comment by bajtos** [comment]
Lovely, LGTM.

Could you please rebase the patch on top of the current master, squash all commits into a single one, and provide a descriptive commit message following the [50/72 rule](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)?

If you don't have time then I can do it myself, just let me know what works best for you.

**Comment by greaterweb** [comment]
Unfortunately I may not have time to complete the work for another week or so. Happy to do it but things are a little busy at the moment with work.

**Comment by bajtos** [comment]
No worries, I did the cleanup myself and landed your patch as a028d9d1. Thank you for the contribution!

**Pull request closed without merging**
