### PR TITLE
Expose the `filter` argument for findById

### PR DESCRIPTION
**Pull request by raymondfeng**
/to @bajtos or @ritch 

This PR depends on https://github.com/strongloop/loopback-datasource-juggler/pull/564

### CODE REVIEW

**Comment by bajtos** [comment]
Please add a unit-test to test that the new `filter` argument works as expected. You can add it for example to [test/model.test.js](https://github.com/strongloop/loopback/blob/bd973def6308a771bdd7212d9a1d7021f3772491/test/model.test.js#L139-L166).

Consider also writing a test capturing the use case of @pulkitsinghal, where `findById` + `filter.include` is used as a workaround for missing role-based filtering in `find`.

**Comment by raymondfeng** [comment]
@bajtos Tests added.

**Comment by raymondfeng** [comment]
@ritch Docs updated.

**Comment by ritch** [comment]
LGTM

**Comment by bajtos** [comment]
:+1:

**Pull request merged**
