### PR TITLE
Revert "Fix description of updateAll response"

### PR DESCRIPTION
**Pull request by angfal**
### Description
This reverts commit 1439446

#### Related issues
- connect to #3717

### Checklist
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
Hello,  thank you for the pull request. I am afraid we cannot revert #2842 because it's required for client code-generators to work, see the discussion in https://github.com/strongloop/loopback/issues/2104.

We need to fix strong-remoting and/or loopback-connector-remote to correctly support anonymously defined types in remote invocations.

**Pull request closed without merging**
