### PR TITLE
Added indexes to acl and user to stop crashing with redis connector [2.x]

### PR DESCRIPTION
**Pull request by penguinpowernz**
Backporting #2368 to the 2.x branch.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by davidcheung** [comment]
@slnode ok to test

**Comment by loay** [comment]
@slnode test please

**Comment by bajtos** [comment]
Please wait for the discussion in  #2368 to resolve before moving forward with this pull request.

**Comment by bajtos** [comment]
The issue is more complex than it seems. I am closing this pull request for now, let's move the discussion to #3011

**Pull request closed without merging**
