### PR TITLE
Apply g.f to literal strings

### PR DESCRIPTION
**Pull request by 0candy**
Backport #2684

### CODE REVIEW

**Comment by 0candy** [comment]
@superkhau @Setogit PTAL

**Comment by superkhau** [comment]
LGTM

**Comment by superkhau** [comment]
@slnode test please

**Comment by superkhau** [comment]
@0candy Please check the CI failures before merging.

**Comment by superkhau** [comment]
@slnode test please

**Comment by 0candy** [comment]
CI failures unrelated to change. Merging PR.

**Pull request merged**
