### PR TITLE
Add templateFn option to User.prototype.verify()

### PR DESCRIPTION
**Pull request by adrien-k**
#### Related issues
This would give a bit more flexibility to User.prototype.verify() email rendering and provide a workaround to the following issue:
- #1138

### Checklist
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Hi @adrien-k, thank you for the pull request, I appreciate the work you have put into this patch. I took a quick look. The approach looks reasonable to me, I'll perform a more detailed review next week.

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
@adrien-k I was cleaning up the code a bit and accidentally closed your patch. My bad! Let's move the discussion to #2937.

**Pull request closed without merging**
