### PR TITLE
Fix "Issues" link in readme

### PR DESCRIPTION
**Pull request by superkhau**
@bajtos @raymondfeng @ritch FYI, I'm merging this without review as this is a simple fix.

### CODE REVIEW

**Comment by superkhau** [comment]
test please

**Comment by superkhau** [comment]
ok to test

**Comment by bajtos** [comment]
:+1:

**Comment by superkhau** [comment]
@bajtos I have no idea why CI is failing though. Should I be concerned?

**Comment by bajtos** [comment]
It looks like a timing problem on Travis, because our Jenkins passed. Don't worry about it.

**Pull request merged**
