### PR TITLE
Drop Node.js 6.x + update Karma and nyc dependencies to their latest versions

### PR DESCRIPTION
**Pull request by bajtos**
### Description

I noticed that `npm install` is reporting security vulnerabilities in our dev dependencies. This pull request updates the relevant packages to their latest version.

Note that we have more outdated dependencies, but updating them is not trivial, therefore I am leaving such updates out of scope of this pull request.

Some of our dependencies are no longer supporting Node.js 6.x, thus I also need to drop Node.js 6.x from the platforms we are testing on our CI.

### CODE REVIEW

**Comment by dhmlau** [comment]
Regarding the CI failure, do we have downstream failures for `loopback-connector-openapi` and `loopback-connector-swagger` before? 

Status for Travis is pending, but when I clicked on Details, they are all passed.

**Comment by bajtos** [comment]
> The jenkins test still run on node 6 and fails. Could you double check? 

I am not sure why that happened. I re-run the build and node 6 seems to be fine now:

> [cis-jenkins] x64 && linux && nvm,8 — Success! (686c6fe)

**Comment by bajtos** [comment]
> Regarding the CI failure, do we have downstream failures for `loopback-connector-openapi` and `loopback-connector-swagger` before? 

I re-run the build and both connectors passed now. I suspect these connectors are calling external services and there was an intermittent networking problem that caused the tests to fail.

**Comment by bajtos** [comment]
> [cis-jenkins] downstream: loopback-sandbox@master — Failed! (686c6fe)

Opened a PR to fix the problem: https://github.com/strongloop/loopback-sandbox/pull/26

> [cis-jenkins] downstream: loopback-example-bluemix@master — Failed! (686c6fe)

Opened a PR to fix the problem: https://github.com/strongloop/loopback-example-bluemix/pull/16

> [cis-jenkins] downstream: lb-con-test-app@master — Failed! (686c6fe)

Opened a PR to fix the problem, the repo is hosted internally inside IBM.

> [cis-jenkins] downstream: bluemix-service-broker@develop — Failed! (686c6fe)
> [cis-jenkins] downstream: gateway-director-bluemix@develop — Failed! (686c6fe)
> [cis-jenkins] downstream: plan-manager@develop — Failed! (686c6fe)

The builds are failing for unrelated errors and IIRC, they have been failing for long time. Let's ignore these downstream dependencies - see https://github.com/strongloop/loopback/pull/4196

**Pull request merged**
