### PR TITLE
Remove dependency on loopback-testing

### PR DESCRIPTION
**Pull request by superkhau**
- Copy depedent source from loopback-testing into test/helpers
- Removed loopback-testing from package.json

### CODE REVIEW

**Comment by superkhau** [comment]
@bajtos Merging without review. Same changes to remove loopback-testing as other projects.

**Comment by superkhau** [comment]
Connect to strongloop-internal/scrum-loopback/issues/688

**Comment by bajtos** [comment]
@superkhau could you please read through `loopback-testing-helper.js` and remove all unused methods/code?

**Comment by superkhau** [comment]
>@superkhau could you please read through loopback-testing-helper.js and remove all unused methods/code?

Yes, status updates at https://github.com/strongloop-internal/scrum-loopback/issues/699.

**Pull request merged**
