### PR TITLE
DRY calls to this.remotes()

### PR DESCRIPTION
**Pull request by pakallis**
DRY calls to `this.remotes()`

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by superkhau** [comment]
Thanks for the contribution, can you sign the CLA please? https://cla.strongloop.com/agreements/strongloop/loopback

**Comment by pakallis** [comment]
@superkhau Looks like jenkins has frozen.

**Comment by superkhau** [comment]
@slnode test please

**Comment by superkhau** [comment]
@slnode test please

**Comment by superkhau** [comment]
@slnode test please

**Comment by bajtos** [comment]
Hello, while this pull request is making the code more clean, which is important, it also does not add any other benefits. On the other hand, it pollutes git history with irrelevant changes, which makes code archaelogy and back-porting more difficult. In my view, we should refactor existing code only as part of some other relevant work (fixing a bug, implementing a new feature). That serves as a natural prioritization where places frequently changed get better over time, and places that don't change can stay in whatever state they are right now, because it doesn't really matter.

(Note that `this.remotes()` returns a cached value, therefore it's a rather cheap call.)

I am closing this patch as rejected.

**Pull request closed without merging**
