### PR TITLE
Add translation strings

### PR DESCRIPTION
**Pull request by 0candy**

### CODE REVIEW

**Comment by 0candy** [comment]
@bajtos PTAL

**Comment by Setogit** [comment]
LGTM
At this stage, all we care is if `slt-globalize -l` ( SG list) passes for all the translated langauges, which is the case.   It's ready for TVT to check the quality of translation..

**Comment by 0candy** [comment]
@Setogit What is the process for translation quality check?

**Comment by Setogit** [comment]
It's up  to the contact between you and your globalization vendor.  The contract usually defines what the vendor should do before the vendor delivers the final translations and based on the deliverable, the client (you) determines to accept or reject based on the mutually agreed criteria.  The vendor won't be paid until your accept it, but the criteria should be fair and mutually agreed before you enter the globalization contract.

**Comment by 0candy** [comment]
@slnode test please

**Comment by 0candy** [comment]
Both node 10 and 12 windows failing on phantomJS error.

**Comment by bajtos** [comment]
> Both node 10 and 12 windows failing on phantomJS error.

I think we should ignore these errors for now.

**Pull request merged**
