### PR TITLE
add setting 'changeModel'

### PR DESCRIPTION
**Pull request by JonDotsoy**
### Description

Now is not possible define a model to save the changes in [Synchronization](http://loopback.io/doc/en/lb2/Synchronization.html), It is a problem as is used rethinkDB because the table use a verical line symbol (-) and it is not permit. see the next error.

> ```
> Table name `Todo-change` invalid (Use A-Za-z0-9_ only) in:
> ```

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by Amir-61** [comment]
@JonDotsoy Please add test t verify your changes. Thanks

**Comment by Amir-61** [comment]
@slnode test please

**Comment by Amir-61** [comment]
The commit message does not follow [the convention](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) which we follow:
```
 First line should be 50 characters or less (saw 53)
```

Also you need to rebase your PR on top of master branch:
```
**  FAIL: feature/add_setting_changemodel_name contains commits from master, rebase needed
**  FAIL: feature/add_setting_changemodel_name is behind master by 1 commits, rebase needed
**  INFO: external contribution, a committer should probably rebase for them
```

**Comment by JonDotsoy** [comment]
Ok. Check this.

**Comment by Amir-61** [comment]
>Ok. Check this.

I do not see any new commits... Also please look into the test failures as well.

**Comment by bajtos** [comment]
I am closing this patch as abandoned. @JonDotsoy feel free to reopen if/when you get time to address the comments above.

**Pull request closed without merging**
