### PR TITLE
README: add Gitter badge

### PR DESCRIPTION
**Pull request by bajtos**
This pull-request adds this badge to README.md:

[Gitter](https://gitter.im/strongloop/loopback?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

Happy chatting.

@raymondfeng @ritch @altsang @chandadharap any objections?
/cc @superkhau

### CODE REVIEW

**Comment by raymondfeng** [comment]
FYI: I added a link under https://github.com/strongloop/loopback/commit/27a6c16c7389acbee66f62cbf7bf7848c02df39e.

I'm fine to add the badge too.

**Comment by bajtos** [comment]
Last call, I'll merge this on Monday if there are no more comments.

**Comment by chandadharap** [comment]
I might have missed an entire discussion on this.

**Comment by bajtos** [comment]
@chandadharap The idea is to move real-time discussions from IRC to Gitter. Gitter provides many advantages over IRC, e.g. web & native clients, chat (message) history and more. This channel is targeted primarily for LoopBack community members, it is a venue where they can help each other. However, we (at least @raymondfeng and me) are lurking there and sometimes help with answering the questions too.

**Comment by chandadharap** [comment]
okay. i followed up. and see that we added it on Express. Hopefully not a distractio, but like you say, the community could help each other.

**Pull request merged**
