### PR TITLE
Pass returned promises in beforeRemote/afterRemote

### PR DESCRIPTION
**Pull request by tvdstaaij**
See #2747.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
@tvdstaaij thank you for the pull request. I am afraid I didn't get the notification, I think you need to mention people in pull request description, on the title. I'll take a look at this patch soon.

**Comment by bajtos** [comment]
@tvdstaaij good news, I have tracked down the problem and sent a PR to fix it in strong-remoting, see https://github.com/strongloop/strong-remoting/pull/363.

**Comment by tvdstaaij** [comment]
@bajtos Nice, would never have found that myself. So this PR is good to go after your PR to strong-remoting is merged?

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
> So this PR is good to go after your PR to strong-remoting is merged?

Yes.

**Comment by bajtos** [comment]
I cleaned up the test a bit and reworded the commit message to follow our conventions. I am closing this pull request in favour of #2820

**Comment by bajtos** [comment]
I have landed the patch to both master (3.0 RC) and 2.x branches. Thank you @tvdstaaij for the contribution!

**Pull request closed without merging**
