### PR TITLE
feat: change hasone relation error message

### PR DESCRIPTION
**Pull request by sujeshthekkepatt**
The current hasone error message is not appropriate one.
So adds a better message.
See more #4278 

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback) 👈

- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html)
- [x] Commit messages are following our [guidelines](https://loopback.io/doc/en/contrib/git-commit-messages.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by sujeshthekkepatt** [comment]
Sorry for the closed PR's some misunderstanding occurred.

**Comment by sujeshthekkepatt** [comment]
@bajtos thanks for the review. Sorry for the formatting problem. I will modify accordingly. I got a confusion on the linter and prettier. That's what happened.

**Comment by sujeshthekkepatt** [comment]
@bajtos seems there is a commit linter issue. Can you check the code now?

**Comment by dhmlau** [comment]
@sujeshthekkepatt, the commit linter error is:
```
**************************************************
**
**  Linting commit logs
**
**  1 problems found:
**    ec1d4ce - Revert "feat: change hasone relation error message": First line should be 50 characters or less (saw 51)
**
**************************************************
```

For details, please refer to our commit message guideline. Thanks! https://loopback.io/doc/en/contrib/git-commit-messages.html

**Comment by sujeshthekkepatt** [comment]
@dhmlau yeah got that. I was hoping to do a squash after the code review. I will update accordingly.

**Comment by sujeshthekkepatt** [comment]
@bajtos any updates?

**Comment by dhmlau** [comment]
@agnes512, thanks for reviewing. 
I'm landing this PR because I saw @bajtos' comments have been addressed.

**Comment by dhmlau** [comment]
@sujeshthekkepatt, thanks for your contribution. Your PR has landed! 🎉

**Pull request merged**
