### PR TITLE
Need index on principalId for performance

### PR DESCRIPTION
**Pull request by rurivera6**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by superkhau** [comment]
See relevant comment https://github.com/strongloop/loopback/pull/2368#issuecomment-253368652

**Comment by bajtos** [comment]
@superkhau Assuming `principalId ` is a foreign key used by a relation, this pull request makes perfect sense to me. We need to tell the database that we will be sending a lot of queries to find a `RoleMapping` record by `principalId` column, and therefore the database should build an index to make the lookup fast.

In fact, I think the juggler should automatically enable `index:true` for all properties that are used  as a foreign key in relations, so that users don't have to do this manually.

I am proposing to:
 - land this pull request as a short-term fix
 - modify relations in juggler to define `index:true` for all foreign keys

@raymondfeng @ritch thoughts?

**Comment by superkhau** [comment]
@bajtos Your proposal sounds good, let's go with that.

@rurivera6 Can you fix the commit errors that are causing CI to fail? `Need index on principalId for performance reasons. : First line should be 50 characters or less (saw 148)` -- See our git commit message guidelines -- http://loopback.io/doc/en/contrib/git-commit-messages.html

**Comment by rurivera6** [comment]
Yes, I will shorten the commit description.  Sorry about that.

**Comment by superkhau** [comment]
@rurivera6 NP, please sign the CLA too: https://cla.strongloop.com/agreements/strongloop/loopback

**Comment by rurivera6** [comment]
CLA is signed.  Let me know if you need anything else from me.  Thank you.

**Comment by superkhau** [comment]
test please

**Comment by rurivera6** [comment]
Yes of course :).  I have already made that change and tested before I submitted the PR.  We are already running with this change in production since without it performance was horrible.  However, without this Pull Request I would need to manually do this every time we rollout a new version of our software since we are using packer/terraform scripts to build and deploy our software.

Thanks again.  Hopefully this gets merged before our next deployment.

**Comment by superkhau** [comment]
@rurivera6 Trying to get it landed, "test please" is how we retrigger CI. ;) The PR is out of date now though, would you like to rebase with master again please?

**Comment by superkhau** [comment]
Also modify the commit message please, getting this error on CI:

```
**************************************************
**
**  Linting commit logs
**
**  1 problems found:
**    23328a2 - Need index on principalId for performance reasons. : First line should be 50 characters or less (saw 148)
**
**************************************************
```

See http://loopback.io/doc/en/contrib/git-commit-messages.html

**Comment by rurivera6** [comment]
I could not for the life of me figure out how to modify the commit message.  There was no rollback, delete or any other options on prior commits.  I finally decided to blow away my entire forked repo and start over.  I will close this and open up a new pull request.  I even tried rebase back a few versions, doing the "--amend" on the commit but to no avail.

**Pull request closed without merging**
