### PR TITLE
Apply g.f to literal strings

### PR DESCRIPTION
**Pull request by Setogit**
@0candy  @superkhau  PTAL

### CODE REVIEW

**Comment by 0candy** [comment]
LGTM

**Comment by Setogit** [comment]
@0candy  thanks. Can anybody in the LoopBack team help?
I'm NOT going to merge this to master because not sure about the process of backporting to v2.x.
I imagine it needs to happen at the same time as this merge to master(v3).

**Comment by superkhau** [comment]
LGTM, we can help with the backporting.

**Comment by superkhau** [comment]
@gunjpan @richardpringle PTAL at the loopback-connector-rest CI failure, something to do with using the same ports.

**Comment by superkhau** [comment]
@rmg Can you look at the http://ci.strongloop.com/job/loopback-connector-jsonrpc/1956/node=0.10,os=amazon/console CI error? Seems like CI is having trouble installing some module -- `npm ERR! Cannot find module 'path-is-inside'`

**Comment by superkhau** [comment]
@rmg Also getting timeouts on http://ci.strongloop.com/job/loopback-workspace/label=amazon-0.10/4825/consoleFull#-8927616347ca194ba-b528-4e74-a19c-5de762bfc5b0

**Comment by superkhau** [comment]
Gonna merge this as these are unrelated failures.

**Pull request merged**
