### PR TITLE
User.resetPassword returns now a 404 NOT FOUND if the email does not exist.

### PR DESCRIPTION
**Pull request by julien-sarazin**
update built-in User.resetPassword regarding #1374 and #947.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by superkhau** [comment]
@julien-sarazin Can you sign the SLA? The tests are also failing. Did you run jshint?

**Comment by superkhau** [comment]
Can you add some tests to verify things are working properly?

**Comment by julien-sarazin** [comment]
Sure. Not possible ATM but i'll try this WE.

**Comment by superkhau** [comment]
Looking forward to it. Thanks.

**Comment by superkhau** [comment]
@julien-sarazin The fix has been merged at https://github.com/strongloop/loopback/pull/1789

**Pull request closed without merging**
