### PR TITLE
update deprecated dep version

### PR DESCRIPTION
**Pull request by dhmlau**
### Description
Some of the dependencies in loopback has deprecated and one of them indicated upgrading to newer version `to avoid a RegExp DoS issue`. 

#### Related issues
https://github.com/strongloop-internal/scrum-apex/issues/126

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by jannyHou** [comment]
i searched through the repo, didn't find the file requires `supertest-as-promised`, but from CI failure log it's still needed:
```
>> Mocha exploded!
>> Error: Cannot find module 'supertest-as-promised'
>>     at Function.Module._resolveFilename (module.js:469:15)
>>     at Function.Module._load (module.js:417:25)
>>     at Module.require (module.js:497:17)
>>     at require (internal/module.js:20:19)
>>     at Object.<anonymous> (D:\workspace\loopback\d60c4a15\test\context-options.test.js:10:49)
>>     at Module._compile (module.js:570:32)
>>     at Module.replacementCompile (D:\workspace\loopback\d60c4a15\node_modules\nyc\node_modules\append-transform\index.js:58:13)
>>     at module.exports (D:\workspace\loopback\d60c4a15\node_modules\nyc\node_modules\default-require-extensions\js.js:8:9)
>>     at Object.<anonymous> (D:\workspace\loopback\d60c4a15\node_modules\nyc\node_modules\append-transform\index.js:62:4)
>>     at Module.load (D:\workspace\loopback\d60c4a15\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
>>     at tryModuleLoad (module.js:446:12)
>>     at Function.Module._load (module.js:438:3)
>>     at Module.require (module.js:497:17)
>>     at require (internal/module.js:20:19)
>>     at D:\workspace\loopback\d60c4a15\node_modules\mocha\lib\mocha.js:222:27
>>     at Array.forEach (native)
>>     at Mocha.loadFiles (D:\workspace\loopback\d60c4a15\node_modules\mocha\lib\mocha.js:219:14)
>>     at MochaWrapper.run (D:\workspace\loopback\d60c4a15\node_modules\grunt-mocha-test\tasks\lib\MochaWrapper.js:51:15)
>>     at D:\workspace\loopback\d60c4a15\node_modules\grunt-mocha-test\tasks\mocha-test.js:86:20
>>     at capture (D:\workspace\loopback\d60c4a15\node_modules\grunt-mocha-test\tasks\mocha-test.js:33:5)
>>     at Object.<anonymous> (D:\workspace\loopback\d60c4a15\node_modules\grunt-mocha-test\tasks\mocha-test.js:81:5)
>>     at Object.<anonymous> (D:\workspace\loopback\d60c4a15\node_modules\grunt\lib\grunt\task.js:255:15)
>>     at Object.thisTask.fn (D:\workspace\loopback\d60c4a15\node_modules\grunt\lib\grunt\task.js:73:16)
>>     at Object.<anonymous> (D:\workspace\loopback\d60c4a15\node_modules\grunt\lib\util\task.js:294:30)
>>     at Task.runTaskFn (D:\workspace\loopback\d60c4a15\node_modules\grunt\lib\util\task.js:244:24)
>>     at Task.<anonymous> (D:\workspace\loopback\d60c4a15\node_modules\grunt\lib\util\task.js:293:12)
>>     at D:\workspace\loopback\d60c4a15\node_modules\grunt\lib\util\task.js:220:11
>>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>>     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
Warning: Task "mochaTest:unit-xml" failed. Use --force to continue.
```

**Comment by ssh24** [comment]
This PR doesn't look correct. Why is there so many changes?

**Comment by jannyHou** [comment]
2.x-latest branch is for release use, to backport commit to LB2.x version, we cherry pick the commit to branch 2.x, not 2.x-latest

**Comment by dhmlau** [comment]
oops.. sorry... i was trying to fix the master branch as well, and accidentally go into the 2.x.

**Pull request closed without merging**
