### PR TITLE
Fix ACL rules with a wildcard match ('*') for model property

### LINKED ISSUE #3953: Adding ACL rule with a wildcard match ('*') for model property doesn't work
The ["Controlling data access" documentation page](https://loopback.io/doc/en/lb3/Controlling-data-access.html#acl-rule-precedence) explains how to apply a rule for all models, but adding this king of a rule doesn't work. Exploring the ACL.checkAccessForContext function, which in charge of checking if the relevant request has the permission to access, shows that there is no lookup for '*' and only for the specific model name.

# Description/Steps to reproduce

Create an ACL rule on one of the boot scripts:
```javascript
module.exports = function(app) {
  app.models.ACL.create({
      model: '*',
      property: '*',
      accessType: '*',
      principalType: 'ROLE',
      principalId: '$everyone',
      permission: 'DENY',
    });
}
```

# Link to reproduction sandbox

# Expected result
Accessing to all models (which not includes other ACL rules) would be denied. 

# Additional information

### PR DESCRIPTION
**Pull request by moshemal**
fixes #3953

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
Hello @moshemal, thank you for the pull request. Could you please add a unit test to verify your fix and sign our CLA here? https://cla.strongloop.com/agreements/strongloop/loopback

I am speaking at a conference this week, will try to review your pull request early next week.

**Comment by moshemal** [comment]
@bajtos It seems that the assertions in the callback functions doesn't effect test results. For example, if I add assert(false) at line 239 the test still pass. 
As Mocha documentation explains one should use the method done()
https://mochajs.org/#asynchronous-code 

Do I miss something?

**Comment by bajtos** [comment]
> It seems that the assertions in the callback functions doesn't effect test results. For example, if I add assert(false) at line 239 the test still pass.
As Mocha documentation explains one should use the method done()
https://mochajs.org/#asynchronous-code
>
> Do I miss something?

Good point! Our test suite for ACLs was written back in time when we don't fully understand how to correctly write async tests; and we did not have time to fix it since then. I think the test change you have described should still trigger a test failure if the test suite is run long enough for all async operations to complete; unfortunately that assertion error would manifest as being caused by a different test. Not pretty :(

The best solution is to split that test into multiple smaller one, so that each test has only one assertion. The second best solution is to use `async.parallel` to wait until both calls of `ACL.checkPermission` finish, and only then call `done()`.

Feel free to ignore the existing test cases in `test/acl.test.js` and write a new one in the style that makes most sense to you. For example, I think it should be possible to use Promise-style async control instead of the older callback (`done`) based.

Please let me know if you need any help with the tests

**Comment by moshemal** [comment]
I fixed the tests in PR #3989
will update this PR with new tests

**Comment by moshemal** [comment]
Yes

**Comment by moshemal** [comment]
@bajtos test added

**Comment by bajtos** [comment]
@moshemal landed, thank you for the contribution ❤️

**Pull request merged**
