### PR TITLE
Issue/#1004

### PR DESCRIPTION
**Pull request by panduroab**
I added an error message when User.resetPassword method recibe a User email that doesn't exist.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by panduroab** [comment]
ok

**Comment by raymondfeng** [comment]
@panduroab Thank you for the patch. Please sign CLA at https://cla.strongloop.com/agreements/strongloop/loopback.

Two more things:

1. Can you add a test case?
2. Can you squash the commits into one?

**Comment by bajtos** [comment]
If I understand this patch correctly, it changes the behaviour of "reset password": before this patch, unknown email is silently ignored. After this patch is landed, unknown emails are reported back to the user.

This has security implications, as an attacker can use the "reset password" form to discover valid user emails.

There was a lengthy blog post published on Coding Horror recently that nicely explains the problem and different POVs: [God Login](http://blog.codinghorror.com/the-god-login/)

My conclusions:
 - There should be a config option to enable this feature.
 - Making the feature enabled by default is a breaking change, therefore we should defer that until 3.x

**Comment by panduroab** [comment]
Thanks @bajtos, now I can understand the code meaning, If that is explained in the documentation would be great. And thanks @raymondfeng I'm going to improve my future contributions.

**Comment by bajtos** [comment]
> If that is explained in the documentation would be great.

I am not sure what exactly would you like to change. Could you please contribute the doc fix yourself? See [Contributing to LoopBack documentation](http://docs.strongloop.com/display/LB/Contributing+to+LoopBack+documentation) to get started.

What's the plan for this PR? Are you keen to finish it, or shall we close it?

**Comment by bajtos** [comment]
@panduroab ping, what's the plan for this pull request? Are you still keen to finish it?

**Comment by panduroab** [comment]
@bajtos you can close this PR.

**Pull request closed without merging**
