### PR TITLE
Update user.js

### PR DESCRIPTION
**Pull request by ambrt**
allow to change all {href} instances in user.verify() mail into generated url instead of just one

connect to #2306

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by ambrt** [comment]
It was requested here also https://github.com/strongloop/loopback/pull/2167

**Comment by richardpringle** [comment]
ok to test

**Comment by superkhau** [comment]
LGTM. Thanks for the contribution! ;)

**Comment by superkhau** [comment]
@ambrt I forgot to check before merging this, can you write a unit test for this change to prevent regressions in the future?

**Pull request merged**
