### PR TITLE
Invalidate AccessTokens on password change

### PR DESCRIPTION
**Pull request by bajtos**
Invalidate all existing sessions (delete all access tokens) after user's password was changed.

This is a back-port of #3018

Connect to strongloop-internal/scrum-loopback#925

cc @loay

### CODE REVIEW

**Comment by pelim** [comment]
this change results in invalidating the tokens on User.save() - please revert this change v2.36.0 works finde for me

**Comment by bajtos** [comment]
@pelim could you please open a new issue with steps for reproducing the problem? See also https://github.com/strongloop/loopback/issues/3034 and https://github.com/strongloop/loopback/issues/3068

**Comment by bajtos** [comment]
@pelim is your problem perhaps related to https://github.com/strongloop/loopback/pull/3053?

**Comment by icy90** [comment]
@bajtos I have experienced the same issue, calling User.save() remove all current access tokens even not change user email or password.

in common/models/user.js: ctx.instance always true when you do User.save()
`  // Full replace of User instance => assume password change.
    // HashPassword returns a different value for each invocation,
    // therefore we cannot tell whether ctx.instance.password is the same
    // or not.
    **var isFullReplaceChangingPassword = !!ctx.instance;**

    ctx.hookState.isPasswordChange = isPartialUpdateChangingPassword ||
      isFullReplaceChangingPassword;`

**Comment by bajtos** [comment]
@icy90 I see. Please open a new github issue for this problem, so that we can move the discussion there, and mention my handle there so that I get email notification.

**Pull request merged**
