### PR TITLE
Increase timeout

### PR DESCRIPTION
**Pull request by jannyHou**
Connect to strongloop-internal/scrum-loopback#988

### CODE REVIEW

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@rmg Increasing timeout does fix those timeout failures. But node_0.10_windows and node_0.12_windows are still failing due to phantomjs Error:


```
ERROR [phantomjs.launcher]: QWindowsContext: OleInitialize() failed:  "COM error 0x80070583  (Unknown error 0x0ffffffff80070583)"

ERROR [phantomjs.launcher]: SetProcessDpiAwareness failed: "COM error 0x80070005  (Unknown error 0x0ffffffff80070005)"
QApplication::regClass: Registering window class 'Qt5ClipboardView' failed. (Class does not exist.)
AddClipboardFormatListener() failed. (Invalid window handle.)
__thiscall QWindowsMessageWindowClassContext::QWindowsMessageWindowClassContext(void): RegisterClass() failed ()
Qt: INTERNAL ERROR: failed to install GetMessage hook: 8, Not enough storage is available to process this command.

ERROR [launcher]: Cannot start PhantomJS
	
INFO [launcher]: Trying to start PhantomJS again (1/2).
ERROR [phantomjs.launcher]: QWindowsContext: OleInitialize() failed:  "COM error 0x80070583  (Unknown error 0x0ffffffff80070583)"

ERROR [phantomjs.launcher]: SetProcessDpiAwareness failed: "COM error 0x80070005  (Unknown error 0x0ffffffff80070005)"
QApplication::regClass: Registering window class 'Qt5ClipboardView' failed. (Class does not exist.)
AddClipboardFormatListener() failed. (Invalid window handle.)

ERROR [phantomjs.launcher]: __thiscall QWindowsMessageWindowClassContext::QWindowsMessageWindowClassContext(void): RegisterClass() failed ()

ERROR [phantomjs.launcher]: Qt: INTERNAL ERROR: failed to install GetMessage hook: 8, Not enough storage is available to process this command.

ERROR [launcher]: Cannot start PhantomJS
	
INFO [launcher]: Trying to start PhantomJS again (2/2).
ERROR [phantomjs.launcher]: QWindowsContext: OleInitialize() failed:  "COM error 0x80070583  (Unknown error 0x0ffffffff80070583)"

ERROR [phantomjs.launcher]: SetProcessDpiAwareness failed: "COM error 0x80070005  (Unknown error 0x0ffffffff80070005)"
QApplication::regClass: Registering window class 'Qt5ClipboardView' failed. (Class does not exist.)
AddClipboardFormatListener() failed. (Invalid window handle.)

ERROR [phantomjs.launcher]: __thiscall QWindowsMessageWindowClassContext::QWindowsMessageWindowClassContext(void): RegisterClass() failed ()

ERROR [phantomjs.launcher]: Qt: INTERNAL ERROR: failed to install GetMessage hook: 8, Not enough storage is available to process this command.

ERROR [launcher]: Cannot start PhantomJS
	
ERROR [launcher]: PhantomJS failed 2 times (cannot start). Giving up.
Warning: Task "karma:unit-once" failed. Use --force to continue.
```

Any thought? thanks!

**Comment by rmg** [comment]
@jannyHou it looks like the Windows version of running out of file descriptors. I'm going to reboot the Windows VMs and then kick off another build - I'm pretty sure that will clear things up.

**Comment by rmg** [comment]
@slnode test please

**Comment by bajtos** [comment]
LGTM, the patch makes the situation better. Even if it's not fixing all issues, it's still an improvement worth landing.

**Comment by bajtos** [comment]
@jannyHou could you please back-port to 2.x?

**Comment by jannyHou** [comment]
@rmg Thanks! and @bajtos sure I will back port it to 2.x

**Pull request merged**
