### PR TITLE
Set application's id property only if it's empty.

### LINKED ISSUE #1689: Application.resetKeys will create a new instance instead of updating a record
When I want to reset keys for a application use `Application.resetKeys`. It will create a new instance instead of updating this instance.

This caused by 'before save' operation hook.
https://github.com/strongloop/loopback/blob/master/common/models/application.js#L95

Maybe it should set the id property just it's empty.

### PR DESCRIPTION
**Pull request by wusuopu**
to @ritch

Close #1689

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by ritch** [comment]
Ok to test

**Comment by ritch** [comment]
This LGTM

**Comment by bajtos** [comment]
@wusuopu could you please add a unit-test to verify your implementation and prevent regressions in the future?

**Comment by wusuopu** [comment]
@bajtos it has added now

**Comment by bajtos** [comment]
Landed via  14e6ec5, thank you for the contribution!

**Pull request closed without merging**
