### PR TITLE
user: throw error if email is not found in reset

### PR DESCRIPTION
**Pull request by yorkie**
Sometimes the user needs to get if someone who wants to reset his password has typed the correct email.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by yorkie** [comment]
can someone take a look at this?

**Comment by raymondfeng** [comment]
I wonder if this feature should be controlled by an option. Telling people that an email doesn't match the users could be a security concern. @ritch WDYT?

**Comment by OwenBrotherwood** [comment]
@raymondfeng @ritch 
Use Case: 
User friendly, maybe.
Hacker friendly, likely.
If it is a guess the username, the attacker obtains immediate feedback that she should try another combination.
It is also a candidate for rate limiting if this is not already done.

**Comment by yorkie** [comment]
How is this pr going?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
@ritch Can you review the PR?

**Comment by ritch** [comment]
This cannot be the default behavior. I'm ok with it being behind a setting.

**Comment by ritch** [comment]
Will re-open once the flag is added @yorkie.

**Pull request closed without merging**
