### PR TITLE
Use new strong-remoting API

### PR DESCRIPTION
**Pull request by 0candy**
Connect to strongloop-internal/scrum-loopback#617

### CODE REVIEW

**Comment by 0candy** [comment]
@bajtos Please review.

Not sure why the windows one failed, it says:
> No identified problem
No problems were identified. If you know why this problem occurred, please add a suitable Cause for it.

I think the other CI failures were pre-existing.

**Comment by bajtos** [comment]
@0candy please rebase on top of the current master, the pre-existing test failures should have been fixed there.

**Comment by bajtos** [comment]
The code change itself LGTM.

**Comment by 0candy** [comment]
@slnode test plesae

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
For posterity, this is what I found in the [console output of the failed build](http://ci.strongloop.com/job/loopback/node=0.12,os=windows/3023/consoleText):

```
<testcase classname="loopback.rest shared methods with default definitions in model-config.json" name="should not be exposed when the definition value is false" time="2.432"><failure><![CDATA[timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
    at null.&lt;anonymous&gt; (D:\workspace\loopback\c502254b\node_modules\mocha\lib\runnable.js:215:19)
    at null.&lt;anonymous&gt; (D:\workspace\loopback\c502254b\node_modules\continuation-local-storage\node_modules\async-listener\glue.js:188:31)]]></failure></testcase>
<testcase classname="loopback.rest shared methods with default definitions in model-config.json" name="should be exposed when the definition value is true" time="2.084"><failure><![CDATA[timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
    at null.&lt;anonymous&gt; (D:\workspace\loopback\c502254b\node_modules\mocha\lib\runnable.js:215:19)
    at null.&lt;anonymous&gt; (D:\workspace\loopback\c502254b\node_modules\continuation-local-storage\node_modules\async-listener\glue.js:188:31)]]></failure></testcase>
```

I don't see any (obvious) problem in the test code that would cause this failure. Is it possible that we create so many ephemeral servers in such a short time, that the Windows OS runs out of free ephemeral ports and therefore the test times out while waiting for a port to get released after a TCP timeout?

@rmg thoughts?

**Comment by bajtos** [comment]
I triggered a new run of CI and all loopback tests passed. @0candy I think you can go ahead and land this.

**Pull request merged**
