### PR TITLE
[DO NOT MERGE] [2.x] CI test

### PR DESCRIPTION
**Pull request by dhmlau**
### Description
CI failed in the downstream repo.  Only changing the README.md to see if it is related to my PR

### CODE REVIEW

**Comment by dhmlau** [comment]
@slnode  test please

**Comment by dhmlau** [comment]
@slnode  test please

**Comment by dhmlau** [comment]
@slnode  test please

**Comment by rmg** [comment]
`strong-mesh-client@master` should be taken care of by strongloop/strong-mesh-client#59 next time this PR is built.

**Comment by rmg** [comment]
Other fixes for downstream failures:
 - [x] strongloop/loopback-connector-swagger#37 (`loopback-connector-swagger@1.x`)
 - [x] strongloop/loopback-connector-swagger#38 (`loopback-connector-swagger@loopback-2.x`)
 - [ ] strongloop/loopback-connector-soap#75 (`loopback-connector-soap@loopback-2.x`)

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode  test please

**Comment by dhmlau** [comment]
@slnode test please

**Comment by bajtos** [comment]
@dhmlau is this patch still relevant? Can we close it?

**Comment by dhmlau** [comment]
@bajtos , sorry, it's no longer needed.  Closing it.  Thanks.

**Pull request closed without merging**
