### PR TITLE
#3114 Update role.json to include missed data types

### PR DESCRIPTION
**Pull request by jdhrivas**
Fix for #3114

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Hi @jdhrivas, thank you for the pull request. Please fix the commit message to follow our [50/72 rule](http://loopback.io/doc/en/contrib/git-commit-messages.html). If you are not familiar with git history manipulation:
 - `git commit --amend` to edit the message
 - `git push -f` to rewrite the history on GitHub.

I am also wondering, how did you discover this bug? Is there a reasonable way how to write a unit-test reproducing your experience, a test that fails on current `master` but passes with your fix?

**Comment by bajtos** [comment]
Ah, I should have read the linked issue first. Here is a code snippet you can use in the test:

```js
it('...', function() {
  // app is usually already available from a before/beforeEach hook,
  // in which case part of this setup can be skipped in the test
  var app = loopback({localRegistry: true, loadBuiltinModels: true});
  var Role = app.registry.getModel('Role');
  app.dataSource('db', {connector: 'memory'});
  app.model(Role, {dataSource: 'db'});

  return Role.create({name: 'ADMIN'})
    .then(function(role) {
      expect(role.toJSON().created).to.be.instanceOf(Date);
    });
});
```

**Comment by jdhrivas** [comment]
@bajtos test passed, should I create a second PR to add new test? or someone on your end can added?

```
it('should store Date to created property', function() {
    // app is usually already available from a before/beforeEach hook,
    // in which case part of this setup can be skipped in the test
    var app = loopback({localRegistry: true, loadBuiltinModels: true});
    var Role = app.registry.getModel('Role');
    app.dataSource('db', {connector: 'memory'});
    app.model(Role, {dataSource: 'db'});

    return Role.create({name: 'ADMIN'})
      .then(function(role) {
        expect(role.toJSON().created).to.be.instanceOf(Date);
      });
  });
```

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
Hmm, I wanted to make few last changes myself. Unfortunately, `git push -f` into your `master` branch closed this pull request :( Let's continue this work in #3161

Please use `git fetch && git reset --hard origin/master` to restore your local `master` branch. Sorry for the mess I created in your fork! When contributing in the future, I recommend to use feature branches - see e.g. [Getting into open source for the first time](http://www.nearform.com/nodecrunch/first-time-with-open-source/)

**Pull request closed without merging**
