### PR TITLE
Update dependencies to their latest versions

### PR DESCRIPTION
**Pull request by bajtos**
cc @strongloop/loopback-dev FYI, I think no review is needed

### CODE REVIEW

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
@slnode test please

**Comment by jannyHou** [comment]
LGTM 👍

**Comment by bajtos** [comment]
Yay, loopback itself is green now 💃 

@jannyHou I added three more commits, could you please review them?

Other than that, I think this patch is ready for landing.

**Comment by bajtos** [comment]
@slnode test please

**Comment by jannyHou** [comment]
👍 loopback itself are all green. Thank you @bajtos Let's land it.

**Pull request merged**
