### PR TITLE
Add replication tests for conflict resolution; run replication tests in the browser too

### PR DESCRIPTION
**Pull request by bajtos**
Connect to #985 

/to @ritch please review

### CODE REVIEW

**Comment by bajtos** [comment]
Few comments:

 - I did not include tests for handling of "deleted" conflicts. If you think it's important, then I can add them next week, possibly in a new pull request

 - It would be nice if `Conflict` provided API for the three ways how conflicts are usually resolved. With the current implementation, I had to look at loopback-example-full-stack to learn what's the correct solution.

 - DOC note: When doing bidirectional sync, it's important to replicate from Client to Server first, so that any conflicts are resolved at the client side.

**Comment by ritch** [comment]
> It would be nice if Conflict provided API for the three ways how conflicts are usually resolved. With the current implementation, I had to look at loopback-example-full-stack to learn what's the correct solution.

Agreed 

LGTM

**Comment by ritch** [comment]
I'm not worried about the delete tests. Also the ordering issue needs to be pretty clear in the docs otherwise it sounds like a bug.

**Comment by bajtos** [comment]
I filled a new issue for the better `Conflict` API - see https://github.com/strongloop/loopback/issues/1188

**Pull request merged**
