### PR TITLE
Emit options to resetPasswordRequest handlers

### PR DESCRIPTION
**Pull request by gausie**
In my use case, I want the different consumers of my API to be able to supply a "callback" url which displays the client's own interface to the password reset flow.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by ritch** [comment]
The change looks innocent enough so I think we can land this as is.

**Comment by ritch** [comment]
OK to test

**Comment by gausie** [comment]
Is there anything holding this up?

**Comment by loay** [comment]
test please

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
Closing in favour of https://github.com/strongloop/loopback/pull/2992

**Pull request closed without merging**
