### PR TITLE
[2.x] Update deprecated dependencies

### PR DESCRIPTION
**Pull request by dhmlau**
### Description

Some of the dependencies in loopback has deprecated and one of them indicated upgrading to newer version to avoid a RegExp DoS issue.

#### Related issues
connect to https://github.com/strongloop-internal/scrum-apex/issues/126

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
ok.  will change it to only include `package.json`.  We thought putting the change in the message.json would fix the test failure.

**Comment by dhmlau** [comment]
@slnode test please
Interestingly, CI passed when I committed yesterday.

**Comment by dhmlau** [comment]
@slnode  test please

**Comment by dhmlau** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@bajtos , CI is still failing on the non-required checks.  Could you please help on this?  Thanks!

**Comment by dhmlau** [comment]
@slnode  test please

**Comment by rmg** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode  test please

**Pull request merged**
