### PR TITLE
Need index on principalId for performance.

### PR DESCRIPTION
**Pull request by rurivera6**
### Description

See #2849.

#### Related issues (eg. strongloop/loopback#2849)

- #2849

### Checklist

- [x] CLA signed
- [x] New tests are added to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] All CI builds are passing

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by rurivera6** [comment]
I had to close the other PR because I could not figure out how to amend previous commits.  I learned my lesson and the description does not exceed 50 on this one.

**Comment by superkhau** [comment]
@rurivera6 Thanks for figuring it out. Let's wait for CI to pass and land this. I updated your message and checked off 3/4 of the landing requirements. :four_leaf_clover:

**Comment by superkhau** [comment]
CI is acting up, 4 hours and its still yellow. I'll try again.

**Comment by superkhau** [comment]
@slnode test please

**Comment by rurivera6** [comment]
You're welcome.  Hopefully this gets merged before our next go-live which is next Tuesday.

**Comment by superkhau** [comment]
@rurivera6 Helped you land the PR (it needed rebasing again) via #2883

**Comment by superkhau** [comment]
@rurivera6 Thanks for the contribution! :+1: As for the release schedule, I'm not sure about this -- @bajtos is doing a lot of work recently for LB3 release, so he will have better insight here.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by superkhau** [comment]
@rmg Why are we getting multiple spam messages from @slnode above?

**Comment by bajtos** [comment]
> You're welcome. Hopefully this gets merged before our next go-live which is next Tuesday.

Released as `loopback@2.36.0`

**Pull request closed without merging**
