### PR TITLE
Replace all the "{href}" placeholders in verify email template

### PR DESCRIPTION
**Pull request by aitoraznar**
Hello,

I needed to send an email with the link in a button and an alternative link in plain text.
So I used a regex to replace all the "{href}" placeholders in verify email template.

Regards

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by loay** [comment]
Can you please keep the commit message to 50 characters or less. 
Also, do you mind adding a quick unit test to catch any future regression? Thanks

**Comment by aitoraznar** [comment]
Ok, I''ll do

**Comment by superkhau** [comment]
Closing as duplicate of https://github.com/strongloop/loopback/pull/2310 (already merged). If you feel the `m` modifier for regex is necessary, please submit another PR and I will get it merged in right away. Thanks for the contribution! ;)

**Pull request closed without merging**
