### PR TITLE
Make the app instance available to connector

### PR DESCRIPTION
**Pull request by SubuIBM**
… app of events

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
@SubuIBM Thank you for the pull request. Please add a unit-test to verify the change and prevent regressions in the future.

You can find existing tests for `app.dataSource` here, please add a new one for your feature: https://github.com/strongloop/loopback/blob/98eed7238db8eb1441fe81dd8ad2ead6a0a68d38/test/app.test.js#L799-L815

**Comment by SubuIBM** [comment]
@bajtos Thanks for the review and comment. I have added the unit-test now. LoopBack rocks and I'm immensely happy to have made my first contribution (howsoever small) !

**Comment by SubuIBM** [comment]
The results of:
mocha test test/app.test.js
....
....
    app.dataSource
      ✓ looks up the connector in `app.connectors`
      ✓ adds data source name to error messages
**✓ adds app reference to the data source object**
....

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Landed via 987f29e (master) and #2687 (2.x). Thank you @SubuIBM for your contribution!

**Pull request closed without merging**
