### PR TITLE
update strong-error-handler

### PR DESCRIPTION
**Pull request by sqlwwx**
on strong-error-handler ^1.0.1
```
{
  "error": {
    "statusCode": 400,
    "name": "Error",
    "message": "username or email is required"
  }
}
```
strong-error-handler ^2.1.0

```
{
  "error": {
    "statusCode": 400,
    "name": "Error",
    "message": "username or email is required",
    "code": "USERNAME_EMAIL_MOBILE_REQUIRED"
  }
}

```

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
Hello @sqlwwx, thank you for the pull request. Note that `loopback` does not ship `strong-error-handler` as a regular dependency, applications are expected to add whatever version of `strong-error-handler` they want to use.

Having said that, I agree it's a good idea to upgrade the strong-error-handler version used by loopback tests. Could you please fix your pull request to keep `strong-error-handler` in `devDepencencies`?

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by sqlwwx** [comment]
@bajtos updated

**Comment by bajtos** [comment]
Landed, thank you for the contribution!

**Pull request merged**
