### PR TITLE
tests for this issue

### PR DESCRIPTION
**Pull request by phairow**
test when object for id, can still generate verifyHref correctly

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by phairow** [comment]
tests for pull request #3253

**Comment by phairow** [comment]
merged this with the other at #3253

**Pull request closed without merging**
