### PR TITLE
Make verifyUserRelations() more robust

### PR DESCRIPTION
**Pull request by mcitdev**
### Description
 Refactoring the verifyUserRelations function to :

- fix the app crash when the "accessTokens" relation is not correctly set up
- use more accurate condition in the first if statement 
- prevent the redundant test of "hasManyTokens" in the function 

See also #3934

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
Thank you @mcitdev for the pull request. The code changes looks good 👍 The commit history was a bit of a mess, I cleaned it up for you and rebased your patch on top of the latest `master`. Let's wait for CI results before landing.

Because you send the PR from your `master` branch, you will need a bit of cleanup work on your side to make your `master` branch up to date with our `master` branch (the upstream).

1. If you don't have strongloop's repository configured as an upstream `remote` yet:
    ```
    $ git remote add upstream https://github.com/strongloop/loopback
    ```

2. Fetch the latest updates from `upstream`:
    ```
    $ git fetch upstream
    ```

3. Hard-reset your master to `upstream`:
    ```
    $ git checkout master
    $ git reset --hard upstream/master
    ```

4. Force-push your changes back to GitHub
    ```
    $ git push -f
    ```

In the future, please create a new feature branch for each pull request. I recommend the following guide for step-by-step instructions showing the recommended contribution workflow: https://www.nearform.com/blog/first-time-with-open-source/

**Comment by bajtos** [comment]
Landed 🎉 Thank you for the contribution ❤️

**Comment by mcitdev** [comment]
I confess that I learned lot about git stuff from you, Thanks @bajtos

**Pull request merged**
