### PR TITLE
Backport/issue580

### PR DESCRIPTION
**Pull request by loay**
Backport fix issue 580

### CODE REVIEW

**Comment by loay** [comment]
@Amir-61 PTAL

**Comment by Amir-61** [comment]
>@Amir-61 PTAL

Connect to https://github.com/strongloop/loopback/pull/2492

The back-porting process LGTM.

I see some more comments from @bajtos in the actual https://github.com/strongloop/loopback/pull/2492, so I leave the the decision to you/ @bajtos  of whether you should apply those changes in this backporting or send another PR; also please check the tests run on CI as well.

Thanks

**Comment by loay** [comment]
doing the back-porting same as in Master. 
I will address the 2 recent comments in a separate PR to avoid confusion

**Comment by Amir-61** [comment]
On the second thought, since you will be sending another PR against master to address @bajtos's comments; I believe it is better to have another backporting for that to `2.x` as well.

Thanks!

**Comment by loay** [comment]
@slnode test please

**Pull request merged**
