### PR TITLE
Passing options.verificationToken to options.templateFn

### PR DESCRIPTION
**Pull request by islamixo**
Validating TypeError: tokenGenerator is not a function

Passing the token to the template function, for example:

You need to build several url to send email template.

user.verify({
// ...
  templateFn: createVerificationEmail,
});

function createVerificationEmail(options, cb) {
  options.verifyMovil = CONFIG.verifyHref + "/other.html?uid=" + options.user.id + ";token=" + options.verificationToken;

  var template = loopback.template(options.template);
  var body = template(options);
  cb(null, body);
}

#### Related issues

- None

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
@islamixo thank you for the updated pull request. I reworded your commit to follow our [50/72 rule](http://loopback.io/doc/en/contrib/git-commit-messages.html). Let's wait for the CI build results and then I am happy to land this patch.

**Comment by bajtos** [comment]
Landed, thank you for the contribution! 🎉

**Pull request merged**
