### PR TITLE
Expose upsertWithWhere

### PR DESCRIPTION
**Pull request by Amir-61**
* Expose upsertWithWhere

Backport of #2539

### CODE REVIEW

**Comment by Amir-61** [comment]
@slnode test please

**Comment by Amir-61** [comment]
* @bajtos @rmg It seems `Loopback@2.x` does not fetch the latest changes from `loopback-datasurce-juggler@2.x`; in other words, it does not fetch the changes we have landed by [this PR](https://github.com/strongloop/loopback-datasource-juggler/pull/1052) in `loopback-datasurce-juggler@2.x`; do we need to release a new npm version for `loopback-datasurce-juggler@2.x` to have the changes in this PR?
* @bajtos @jannyHou When I test this PR using `npm link` to the latest commit of `loopback-datasource-juggler@2.x` on my local machine, all tests pass except [this relationship test](https://github.com/strongloop/loopback/blob/a6f8ec672dbffcd7a11db40c464b949b1b9a1b62/test/relations.integration.js#L912-L927) in  `test/relations.integration.js`, which is definitely irrelevant to this PR. Can we merge this PR since the failure is irrelevant to this PR?

**Comment by Amir-61** [comment]
Oh Please ignore my earlier [comment#2722](https://github.com/strongloop/loopback/pull/2722#issuecomment-245082255); it seems they are pulling the latest changes from `loopback-datsource-juggler@2.x`now and it seems they started passing now.

@bajtos There was some small merge conflicts. PTAL this back-porting PR.

**Comment by bajtos** [comment]
LGTM.

**Comment by mountain1234585** [comment]
@Amir-61  Thanks a lot for getting this in.

**Comment by Amir-61** [comment]
No Problem. Enjoy it 🎊

**Comment by Amir-61** [comment]
Relate to https://github.com/strongloop/loopback/pull/2729

**Pull request merged**
