### PR TITLE
simplify the implementation for app.remoteObjects

### PR DESCRIPTION
**Pull request by yorkie**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by jannyHou** [comment]
@yorkie Thank your for contribution, could you rebase your code please:) it's failing on travis ci.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by jannyHou** [comment]
@yorkie hmm...I am reviewing your pr and a little confused, is there any particular benefit that using `reduce()` here instead of `forEach()` ?

**Comment by yorkie** [comment]
> Thank your for contribution, could you rebase your code please:) it's failing on travis ci.

Ah..? The CI fails is not related with changes in this pr. I do not understand clear.

>  is there any particular benefit that using reduce() here instead of forEach() ?

In strictly, here the function `remoteObjects` keeps to the semantics of `reduce` than `forEach` to compute a value and return?

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@yorkie I understand that it's not your code that cause the failure, the thing is recently loopback project change from jshint to eslint, so the old linter test is not valid any more. 
The actual test cases only run after linter test pass. Could you rebase your code with the latest commit from master? Thanks for understanding.

**Comment by yorkie** [comment]
Of course, this is reasonable :-)

**Comment by yorkie** [comment]
Rebased @jannyHou Thanks for your guide

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
hey @yorkie, from the ci test, there one failed test case of your code:
My local error log is more detailed:
```
 1) app app.model(Model) uses singlar name as app.remoteObjects() key:
     AssertionError: expected undefined to deeply equal { Object (color) }
      at Context.<anonymous> (C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback\test\app.test.js:570:38)
      at callFn (C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback\node_modules\mocha\lib\runnable.js:315:21)
      at Test.Runnable.run (C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback\node_modules\mocha\lib\runnable.js:308:7)
      at Runner.runTest (C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback\node_modules\mocha\lib\runner.js:422:10)
      at C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback\node_modules\mocha\lib\runner.js:533:12
      at next (C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback\node_modules\mocha\lib\runner.js:342:14)
      at C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback\node_modules\mocha\lib\runner.js:352:7
      at next (C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback\node_modules\mocha\lib\runner.js:284:14)
      at C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback\node_modules\mocha\lib\runner.js:315:7
      at done (C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback\node_modules\mocha\lib\runnable.js:276:5)
      at callFn (C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback\node_modules\mocha\lib\runnable.js:333:7)
      at Hook.Runnable.run (C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback\node_modules\mocha\lib\runnable.js:308:7)
      at next (C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback\node_modules\mocha\lib\runner.js:298:10)
      at Immediate._onImmediate (C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback\node_modules\mocha\lib\runner.js:320:5)

``` 
This is the full log from ci test: http://ci.strongloop.com/job/loopback/node=4.x,os=amazon/3232/consoleFull
Could you take a look?

And @superkhau could you take a quick review of this pr(only a few lines), does it benefit us much if replacing `array.forEach` with `array.reduce`? My concern is I haven't seen anywhere else in loopback using `array.reduce`, is it proper to use it in terms of code consistent? Thanks!

**Comment by yorkie** [comment]
> And @superkhau could you take a quick review of this pr(only a few lines), does it benefit us much if replacing array.forEach with array.reduce? My concern is I haven't seen anywhere else in loopback using array.reduce, is it proper to use it in terms of code consistent? Thanks!

To keep consistent, we should update all parts if `reduce` is verified to be instead of `forEach`.

**Comment by superkhau** [comment]
@jannyHou Reduce is fine since is in the ECMA 5.1 spec. Just make sure the intent is correct and that the results are verifiable via testing.

**Comment by jannyHou** [comment]
@yorkie any update about fix the failing test case:) ?

**Comment by yorkie** [comment]
I might give some update tonight, sorry @jannyHou

**Comment by bajtos** [comment]
Hello, while this pull request is making the code more clean, which is important, it also does not add any other benefits. On the other hand, it pollutes git history with irrelevant changes, which makes code archaelogy and back-porting more difficult. In my view, we should refactor existing code only as part of some other relevant work (fixing a bug, implementing a new feature). That serves as a natural prioritization where places frequently changed get better over time, and places that don't change can stay in whatever state they are right now, because it doesn't really matter.

I am closing this patch as rejected.

**Pull request closed without merging**
