### PR TITLE
Add email validation to User password reset method

### PR DESCRIPTION
**Pull request by leandropio**
I've extended User with **validateEmail** method and used it in the **User.resetPassword** to check validity of the email inputed in _options.email_.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
Hello @leandropio, thank you for the pull request and sorry for our silence!

I don't understand what are you trying to achieve. The email should be validated at the time when `User` is created (or updated). Therefore if you call `resetPassword` with an invalid email, the operation will fail since there is no user with such invalid email.

Could you please elaborate more on the issue you are trying to address?

We also need you to add unit-tests for your changes before we can land this pull request.

Please let us know if you are still interested in working on this problem.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
I am closing this pull request as abandoned.

**Pull request closed without merging**
