### PR TITLE
Changes to loopback lib/persisted_model.js to expose "upsertWithWhere" as REST API

### PR DESCRIPTION
**Pull request by mountain1234585**
Hi Raymond,

Kindly review the changes to the lib/persisted-model.js . I could see the new method appearing in the explorer and perform the operation.

Regards,
Sonali Samantaray

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by mountain1234585** [comment]
@raymondfeng  
 Can you please review this PR.

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by mountain1234585** [comment]
@Amir-61  
cc @superkhau @bajtos

Can you pls review this PR as well ?

**Comment by mountain1234585** [comment]
Have changes in another PR. https://github.com/strongloop/loopback/pull/2539

Closing this, since the clahub was reporting errors even after adding all signatures and had too many conflicts to resolve.

**Pull request closed without merging**
