### PR TITLE
fix(user): Use User.createAccessToken in User.resetPassword

### PR DESCRIPTION
**Pull request by JonnyBGod**
### Description

This makes it possible to use an overwritten User.createAccessToken function.

#### Related issues

- None

### Checklist

- [no need] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by JonnyBGod** [comment]
Link error is not related to my changes

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Closing in favour of https://github.com/strongloop/loopback/pull/3120

**Pull request closed without merging**
