### PR TITLE
loopback.token options.searchDefaultTokenKeys

### PR DESCRIPTION
**Pull request by OwenBrotherwood**
https://github.com/strongloop/loopback/issues/1326

Signed-off-by: Owen Brotherwood <owen@brotherwood.biz>

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by OwenBrotherwood** [comment]
@bajtos Looks like "All is well" with this PR.
The actual code change is trivial: the tests took my time: but I am gratefull for the experience.
Let us see if you like the tests

**Comment by ritch** [comment]
Can you squash your commits into one? Otherwise this LGTM

**Comment by OwenBrotherwood** [comment]
@ritch 
Git was another learning curve for me in order to [http://stackoverflow.com/questions/4603221/git-merge-in-only-one-commit](git merge in only one commit Answer7)  [http://pastebin.com/nnpPf7cf](pastebin).
I followed the method described, ie my branch loopback-issue-1326 -> my master loopback.

I will double check and post what I found

**Comment by ritch** [comment]
@OwenBrotherwood I appreciate the effort here. Thanks!

Using interactive rebase (`git rebase -i master`) you can accomplish just about anything (probably what @bajtos used) as far as rewriting history for a branch. When we hit the green button on github it will create a (annoying, and not so useful) merge commit. We are OK with these since we get other benefits from the green button style merge.

All you have to do is ensure that only one commit shows up in github and we'll take care of the rest. I usually do this by `git rebase -i` setting all commits besides the first to `s` or `squash`.

**Comment by OwenBrotherwood** [comment]
@ritch This is the output. If ok, I will push
```
ob_000@OB-X1-CARBON ~/loopback (master)
$ git rebase -i master # note, starts vi with the cut and paste below
Successfully rebased and updated refs/heads/master.
```

```
noop

# Rebase 1469958..1469958 onto 1469958
#
# Commands:
#  p, pick = use commit
#  r, reword = use commit, but edit the commit message
#  e, edit = use commit, but stop for amending
#  s, squash = use commit, but meld into previous commit
#  f, fixup = like "squash", but discard this commit's log message
#  x, exec = run command (the rest of the line) using shell
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
~
~
~
~
~\loopback\.git\rebase-merge\git-rebase-todo [unix] (19:13 12/05/2015)   1,1 All
```

**Comment by OwenBrotherwood** [comment]
@ritch 
Hmmm, I deceided to "do it": no real change seen....
```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean

ob_000@OB-X1-CARBON ~/loopback (master)
$ git push origin master
Username for 'https://github.com': owenbrotherwood
Password for 'https://owenbrotherwood@github.com':
Everything up-to-date

ob_000@OB-X1-CARBON ~/loopback (master)
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
```

**Comment by OwenBrotherwood** [comment]
@ritch Sorry for the 'spam'
I have:
- forked strongloop/loopback to coolPlask/loopback
- created a pull request from OwenBrotherwood/loopback (master) coolPlask/loopback  (master)
- accepted the green button on coolPlask/loopback

Result is @ https://github.com/coolPlask/loopback which looks "ok" at first glance

**Comment by bajtos** [comment]
I am personally not a fan of this new style of unit-tests, in particular splitting the test scenario code from the test itself makes the test code difficult to read. I would personally prefer to refactor the existing helpers in [test/access-token.test.js](https://github.com/strongloop/loopback/blob/28a0537e81268e8c52504c2522c7984f4f26f969/test/access-token.test.js#L341-L409) and add the new tests there too.

It is also adding third way how to write unit-tests, I think this may become confusing pretty soon.

Having said that, I am open to experimentation. If @ritch thinks this is a good thing to try, then I don't object.

**Comment by bajtos** [comment]
Related discussion: #1381.

**Comment by OwenBrotherwood** [comment]
@bajtos I agree with your comments. 

I had to create a test but the present test was confusing for myself, I had to build up "what I felt" was right.
I do not think the developers should _just_ accept my suggestion: I have no problem in creating another test, with no use of the new test/lib, a monolithic test, and will push as soon as @ritch gets time to give his comment. Let us do it right.
Please note: there is a _very_ carefull ananlysus of what is to be tested and not that an access_token is available in a req: this is the most important item in the test.

FYI that should be just a comment with no need for repy as it would confuse this issue (I just needed a place to inform without having to send emails or other 'noise'):
 I have a mocha_test branch prepared in my fork such that I can produce suggestions _without_ pr's and within the confines of making too much noise for @bajtos and @ritch ie PR as an issue if I am ready followed by an actual PR when the issue is ready for final commitment or rejection.
The tests will be for any AAA issues I find and I still need to make an LDAP test for loopback-passport

**Comment by OwenBrotherwood** [comment]
@bajtos Monolythic version pushed. There _may_ be extra commits in the push I'm afraid.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by OwenBrotherwood** [comment]
@bajtos Can we pull request or close: I need to have a clean master (I made the mistake from making a push request from master and not an issue branch)
For me, there is no problem with either. 
https://github.com/strongloop/loopback/issues/1326#issuecomment-102144643 contains all the work done

**Pull request closed without merging**
