### PR TITLE
Validate ownership if parent model userId matches userId

### PR DESCRIPTION
**Pull request by jsheely**
If a model belongsTo a model that then belongsTo a user that userId should be enough to validate $owner ACL

Perhaps in an ideal world we would walk the belongsTo tree until we get to the top or hit the first derived class of User.

### CODE REVIEW

**Comment by fabien** [comment]
@jsheely it looks like this PR would require the `fromKey` to be `userId` - however, this is not always the case, since you can subclass User (say, as Account). Your patch would prevent this from working.

**Comment by jsheely** [comment]
I'm not sure what the ```fromKey``` is exactly. I assume it has something to do with the user being able to set the foreign key to whatever they want. 

In either case I refactored the process as I noted originally to walk the ```belongsTo``` tree in order to find a suitable user model and then use that to match the ```user.id``` against the ```userId``` as it was working originally.

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@jsheely thank you for the pull request. Please add unit-tests to demonstrate that your implementation works as intended and also to prevent regressions in the future.

I am personally not familiar with this part of code. @raymondfeng could you please review this change yourself?

**Comment by bajtos** [comment]
Closing as abandoned.

**Pull request closed without merging**
