### PR TITLE
fix typo "PeristedModel"

### PR DESCRIPTION
**Pull request by xrstf**
This seems to be a typo. Could not find a ``PeristedModel`` anywhere.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by crandmck** [comment]
This is clearly just a typo fix.  LGTM, but since it involves a code change, I'm going to defer to a dev.. @superkhau can you pls merge? 

And thanks, @xrstf !

**Comment by bajtos** [comment]
Landed, thank you for the contribution!

**Pull request merged**
