### PR TITLE
Addresses #94 - adds a bit more text to filter

### PR DESCRIPTION
**Pull request by cfjedimaster**
### Description

Addresses #94 

Adds a bit more description to the filter text fields to make it more obvious what is expected there.

#### Related issues

- None

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

No new tests were written as this just modified a label - if that is wrong, let me know.

### CODE REVIEW

**Comment by bajtos** [comment]
Hey @cfjedimaster, thank you for the pull request! I'll take a look and review it in the next few days.

**Comment by bajtos** [comment]
@cfjedimaster for starter, please make sure `npm test` passes on your machine. Some of the lines are too long now - see e.g. https://travis-ci.org/strongloop/loopback/jobs/203503716#L596.

**Comment by cfjedimaster** [comment]
Ugh - I apologize - I honestly thought this was a tiny string change.

**Comment by bajtos** [comment]
@cfjedimaster sorry for closing the pull request. I wanted to squash the commit history for you, unfortunately when a pull request is opened from the `master` branch, github closes it after `git push -f` :(

I opened a new pull request to land the change - see #3218

BTW #94 is a very old pull request that don't seem to be related to this change. Did you perhaps want to refer to issue 94 in a different repository?

**Pull request closed without merging**
