### PR TITLE
Hide verificationToken

### PR DESCRIPTION
**Pull request by gausie**
We should never be showing this publically.

### CODE REVIEW

**Comment by gausie** [comment]
I don't really understand how the automated tests work - none of them have actually failed.

**Comment by bajtos** [comment]
Hi @gausie, could you please rebase your patch on top of the current master and add a unit-test covering your change? See https://github.com/strongloop/loopback/commit/5b50a99eb366f2af36c6a5b6479adacc04fc1547 for inspiration.

As for the automated tests, our Jenkins CI server is not very stable these days. Make sure all tests pass on your machine and on Travis CI.

**Comment by bajtos** [comment]
@ritch @raymondfeng you are more familiar with user verification process than I am. Do you see any reason why it may be a bad idea to hide "verificationToken" from User JSON?

**Comment by gausie** [comment]
Rebased and unit test added.

**Comment by bajtos** [comment]
@gausie could you please squash the commits into a single one?

Note that `!userJson.verificationToken` is true when the token has a falsy value. You should use `!('verificationToken' in userJson)` instead.

I am wondering if we need to go through the whole `verify` process in the unit-test, isn't it enough to set the property and then check it's not serialized to JSON?

```js
var user = new User({email: 'bar@bat.com', password: 'bar', verificationToken: 'a-token' });
var data = user.toJSON();
assert(!('verificationToken' in data));
```

**Comment by gausie** [comment]
@bajtos, have followed both of your recommendations

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
Landed, thank you @gausie for your contribution!

**Pull request merged**
